---
version: '3.1'

volumes:
    prometheus_data: {}

services:
    prometheus:
        image: prom/prometheus:v2.34.0
        volumes:
            - ./prometheus/:/etc/prometheus/
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.max-block-duration=30m'
            - '--storage.tsdb.min-block-duration=30m'
            - '--web.enable-lifecycle'
            - "--web.enable-admin-api"
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
            - 9081:9090

    thanos-sidecar:
        image: quay.io/thanos/thanos:v0.25.2
        volumes:
            - prometheus_data:/prometheus
            - ./prometheus/:/etc/prometheus/
        command:
            - 'sidecar'
            - '--tsdb.path=/prometheus'
            - '--prometheus.url=http://prometheus:9090'
            - '--grpc-address=0.0.0.0:10091'
            - '--http-address=0.0.0.0:10902'
            - "--reloader.config-file=/etc/prometheus/_prometheus.yml"
            - "--reloader.config-envsubst-file=/etc/prometheus/prometheus.yml"
        depends_on:
            - prometheus
        restart: always
        environment:
          BASIC_AUTH: "ilikerandompasswords"
          AWS_ACCOUNT_ALIAS: "aws-account-alias"
          PRODUCT: aws-test
